version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      - run: apt update && apt add git
      - checkout
      - run: git submodule sync && git submodule update --init
      - run: rm -fr $HUGO_BUILD_DIR && git worktree add -B gh-pages $HUGO_BUILD_DIR origin/gh-pages
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - run: git config --global user.email "hello@xn--studioralit-hbbe.com" && git config --global user.name "CircleCI Bot"
      - run: cd $HUGO_BUILD_DIR && git add --all && git commit -m "Automated publish to gh-pages [ci skip]" && git push