---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: data/carousel
  label: Carousel data
  create: all
  match: "**/*"
  new_doc_ext: ".json"
- type: directory
  path: static/img
  label: Images
  create: all
  match: "**/*"
  new_doc_ext: ".jpeg"
- type: directory
  path: content/portfolio
  label: Portfolio
  create: documents
  match: "**/*"
  templates:
  - project
upload_dir: static/img/portfolio
public_path: img
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: docs
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
