---
label: Products
hide_body: true
fields:
- type: field_group_list
  name: Products
  label: Products
  fields:
  - type: text
    name: id
    label: id
    config:
      required: true
  - type: text
    name: name
    label: name
  - type: number
    name: price
    label: price
  - type: file
    name: image
    label: image
  - type: text
    name: description
    label: description
  - type: text
    name: product_url
    label: product_url
  - name: idd
    type: select
    default: []
    config:
      required: false
      options: []
      source:
        type: pages
        section: portfolio
        file: 
        path: 
    label: idd
pages:
- data/products.json
