---
label: Project
hide_body: false
display_field: project
fields:
- type: text
  name: title
  label: Title of the project
- type: text
  name: project
  label: Project Unique Code
  description: This is an internal identifier of the project. It shall be unique
- type: boolean
  name: showonlyimage
  label: showonlyimage
  description: if activated the project will appear on main page without text summary
- type: file
  name: image
  label: Main image for the project
  description: This image will appear on main page for the project.
- type: boolean
  name: carousel
  label: Activate carousel
  description: Will active carousel. Needs Projects carousel data to work
  default: false
- type: number
  name: weight
  label: Number of project
  description: this define the position it will appear on main page
- name: Description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
  description: text that appear on main page over image
- type: datetime
  name: date
  label: date
  config:
    required: true
  default: now
