---
label: Project
hide_body: false
display_field: project
fields:
- type: boolean
  name: showonlyimage
  label: showonlyimage
- type: file
  name: image
  label: image
- type: datetime
  name: date
  label: date
- type: text
  name: title
  label: title
- type: boolean
  name: carousel
  label: carousel
- type: text
  name: project
  label: project
- type: number
  name: weight
  label: weight
- name: Description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
  description: text that appear on main page over image
